### ISSUE TITLE
I don't understand how to install it?

### ISSUE THREAD

**Issue by Cerefka** [AllJavi/tartarus-startpage#1]
Can you tell me how to do that?

**Comment by AllJavi** [comment]
Yeah, well, this type of project is usually created to replace the default new page tab in browsers. The problem is that there's no default option to set it up, so you need a plugin to do it. I use Firefox with the [new-tab-override](https://addons.mozilla.org/es/firefox/addon/new-tab-override/) plugin, but there are some alternatives for other browsers like [custom-new-tab](https://chrome.google.com/webstore/detail/custom-new-tab/lfjnnkckddkopjfgmbcpdiolnmfobflj) in Chrome. Once you have the plugin installed, you just enter the live URL of the repository (or your forked URL), and you're ready to go. Change the configuration as you like and enjoy!

**Comment by rahaaatul** [comment]
Can it be done locally with edge browser? @AllJavi

**Comment by AllJavi** [comment]
I don't know if you can do it locally because for safety reasons some extensions don't let you use files as new tabs, but probably you could do the same as I responded before with this edge plugin [custom new tab](https://microsoftedge.microsoft.com/addons/detail/custom-new-tab/onagfgjlokaciajhjmajljcfanonbmia)

**Comment by rahaaatul** [comment]
> I don't know if you can do it locally because for safety reasons some extensions don't let you use files as new tabs, but probably you could do the same as I responded before with this edge plugin [custom new tab](https://microsoftedge.microsoft.com/addons/detail/custom-new-tab/onagfgjlokaciajhjmajljcfanonbmia)

I have pulled request #3 

You can easily set it locally now.
