### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by DaitiDay** [AllJavi/tartarus-startpage#2]
Is there a way to change the default search engine, the colors of the title of each "page" (meaning chill, design, dev, myself in the default config) and the backgroud color?

**Comment by AllJavi** [comment]
Yessss, but you will need to create your own fork to change the code, because there isn't any option in the config file to do that. I will let you here where to make the changes in the code:
- Background color: 
  - [style.css:l36](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/css/style.css#L36): `--bg: #282828;`
  - [tabs.component.js:l89](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/components/tabs/tabs.component.js#L89C7-L89C17): `background: #282828;`
  - [tabs.component.js:l117](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/components/tabs/tabs.component.js#L117): `background: #282828;`
- Tabs colors:
  - [style.css:l35](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/css/style.css#L35C5-L35C23): `--accent: #a9b665;` (this change the first tab color)
  - [tabs.component.js:l145-l187](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/components/tabs/tabs.component.js#L145): `.categories ul:nth-child(2) {--flavour: #e78a4e;}` (the index of the child is the index of the tab)
  - [statusbar.component.js:l111-ll153](https://github.com/AllJavi/tartarus-startpage/blob/0c4af8f1ee26d2a9e6551abf42f69e0a0fdc4510/src/components/statusbar/statusbar.component.js#L111C19-L111C19): `     #tabs ul li[active]:nth-child(2) ~ li:last-child {--flavour: #e78a4e;}` (this is the same as previous but for the status bar colors)
  
I know is a little bit messy but those are the rules, I hope it helps.
